create table "public"."brackets" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team1" bigint not null,
    "team2" bigint not null,
    "team1_score" bigint,
    "team2_score" bigint,
    "court" bigint,
    "round" bigint
);


alter table "public"."brackets" enable row level security;

CREATE UNIQUE INDEX brackets_pkey ON public.brackets USING btree (id);

alter table "public"."brackets" add constraint "brackets_pkey" PRIMARY KEY using index "brackets_pkey";

alter table "public"."brackets" add constraint "public_brackets_team1_fkey" FOREIGN KEY (team1) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."brackets" validate constraint "public_brackets_team1_fkey";

alter table "public"."brackets" add constraint "public_brackets_team2_fkey" FOREIGN KEY (team2) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."brackets" validate constraint "public_brackets_team2_fkey";

grant delete on table "public"."brackets" to "anon";

grant insert on table "public"."brackets" to "anon";

grant references on table "public"."brackets" to "anon";

grant select on table "public"."brackets" to "anon";

grant trigger on table "public"."brackets" to "anon";

grant truncate on table "public"."brackets" to "anon";

grant update on table "public"."brackets" to "anon";

grant delete on table "public"."brackets" to "authenticated";

grant insert on table "public"."brackets" to "authenticated";

grant references on table "public"."brackets" to "authenticated";

grant select on table "public"."brackets" to "authenticated";

grant trigger on table "public"."brackets" to "authenticated";

grant truncate on table "public"."brackets" to "authenticated";

grant update on table "public"."brackets" to "authenticated";

grant delete on table "public"."brackets" to "service_role";

grant insert on table "public"."brackets" to "service_role";

grant references on table "public"."brackets" to "service_role";

grant select on table "public"."brackets" to "service_role";

grant trigger on table "public"."brackets" to "service_role";

grant truncate on table "public"."brackets" to "service_role";

grant update on table "public"."brackets" to "service_role";


